core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('logar/', views.logar, name='logar'),

    # Buffet
    path('buffet/', views.buffet, name='buffet'),
    path('buffet/pedido/', views.criar_pedido, name='criar_pedido'),
    path('buffet/baixar_pedido/<int:pk>', views.baixar_pedido, name='baixar_pedido'),
    path('buffet/cancelar_pedido/', views.cancelar_pedido, name='cancelar_pedido'),
    # Cozinha
    path('cozinha_quente/', views.cozinha_quente, name='cozinha_quente'),
    path('cozinha_fria/', views.cozinha_fria, name='cozinha_fria'),
    path('buffet/liberar_pedido/<int:pk>', views.liberar_pedido, name='liberar_pedido'),
    # Enquetes
    path('enquete_clientes/', views.enquete_clientes, name='enquete_clientes'),
    path('enquete_clientes/salvar', views.salvar_enquete_clientes, name='salvar_enquete_clientes'),
    path('enquete_funcionarios/', views.enquete_funcionarios, name='enquete_funcionarios'),
    ]

gerencia/urls.py
from django.urls import path
from . import views

app_name = 'gerencia'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # Itens
    path('itens/', views.listar_itens, name='listar_itens'),
    path('itens/cadastro/', views.cadastrar_item, name='cadastrar_item'),
    path('itens/excluir/<int:pk>', views.excluir_item, name='excluir_item'),
    path('itens/atualizar/<int:pk>', views.atualizar_item, name='atualizar_item'),
    #Configurações
    path('configuracoes/', views.configuracoes, name='configuracoes'),
    path('configuracoes/salvar/', views.salvar_configuracoes, name='salvar_configuracoes'),
    path('sair/', views.sair, name='sair'),
    # Enquetes
    path('enquete_clientes/resultado', views.resultado_enquete_clientes, name='resultado_enquete_clientes'),
    path('enquete_funcionarios/resultado', views.resultado_enquete_funcionarios, name='resultado_enquete_funcionarios'),

]

pedidostipico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('dashboard/', include('gerencia.urls', namespace='gerencia')),
]

gerencia/models.py
from django.db import models


class Configuracoes(models.Model):
    taxa_atualizacao = models.IntegerField('Taxa de atualização automática')
    data_atualizacao = models.DateTimeField('Data de Atualização', auto_now=True)

    class Meta:
        verbose_name = 'Configuração'
        verbose_name_plural = 'Configurações'

gerencia/forms.py
from django import forms
from .models import Configuracoes

class ConfiguracoesForm(forms.ModelForm):
    taxa_atualizacao = forms.IntegerField(label='Atualização Automática (seg)')

    class Meta:
        model = Configuracoes
        fields = '__all__'

gerencia/views.py
from django.contrib.sessions.models import Session
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from core.forms import ItemForm
from .forms import ConfiguracoesForm
from core.models import Item, PedidoAtrasado, Pedido, EnqueteClientes, EnqueteFuncionarios
from .models import Configuracoes
from datetime import datetime, timedelta
from django.utils import timezone
from django.db.models import Sum

@login_required(login_url='/logar/')
def dashboard(request):
    User = request.user
    itens = Item.objects.all()
    pedidos_atrasados = PedidoAtrasado.objects.all()
    pedidos = Pedido.objects.all()
    contexto = {
        'titulo_pagina': 'Gestão de Pedidos',
        'usuario': User,
        'itens': itens,
        'pedidos': pedidos,
        'total_pedidos': pedidos.count(),
        'total_pedidos_cancelados': pedidos.filter(situacao='Cancelado').count(),
        'pedidos_atrasados': pedidos_atrasados,
        'total_pedidos_atrasados': pedidos_atrasados.count(),
    }
    return render(request, 'gerencia/dashboard.html', contexto)

@login_required(login_url='/logar/')
def sair(request):
    logout(request)
    return render(request, 'core/index.html')

@login_required(login_url='/logar/')
def cadastrar_item(request):
    form = ItemForm(request.POST or None)
    if str(request.method) == 'POST':
        if form.is_valid():
            form.save()
            return redirect('gerencia:listar_itens')
    contexto = {
        'titulo_pagina': 'Cadastro de Itens',
        'titulo': 'Inclusão de novo item',
        'form': form,
    }
    return render(request, 'gerencia/cadastro_item.html', contexto)

@login_required(login_url='/logar/')
def listar_itens(request):
    itens = Item.objects.all()
    contexto = {
        'titulo_pagina': 'Relação de Itens',
        'titulo': 'Relação de Itens Cadastrados',
        'itens': itens,
    }
    return render(request, 'gerencia/itens.html', contexto)

@login_required(login_url='/logar/')
def excluir_item(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if str(request.method) == 'POST':
        item.delete()
        return redirect('gerencia:listar_itens')
    return render(request, 'gerencia/itens.html')

@login_required(login_url='/logar/')
def atualizar_item(request, pk):
    item = get_object_or_404(Item, pk=pk)
    form = ItemForm(request.POST or None, instance=item)
    if str(request.method) == 'POST':
        if form.is_valid():
            form.save()
            return redirect('gerencia:listar_itens')
    contexto = {
        'form': form,
        'id_item': pk,
    }
    return render(request, 'gerencia/atualiza_item.html', contexto)

@login_required(login_url='/logar/')
def configuracoes(request):
    configuracoes = Configuracoes.objects.filter(pk=1)
    form = ConfiguracoesForm(request.POST or None)
    contexto = {
        'titulo_pagina': 'Configurações Gerais do Sistema',
        'form': form,
       }
    return render(request, 'gerencia/configuracoes.html', contexto)


@login_required(login_url='/logar/')
def salvar_configuracoes(request):
    configuracoes = get_object_or_404(Configuracoes, pk=1)
    form = ConfiguracoesForm(request.POST or None, instance=configuracoes)
    if str(request.method) == 'POST':
        if form.is_valid():
            form.save()
            return redirect('gerencia:configuracoes')
    contexto = {
        'form': form,
    }
    return render(request, 'gerencia/configuracoes.html', contexto)

@login_required(login_url='/logar/')
def resultado_enquete_clientes(request):
    hoje = datetime.now(tz=timezone.utc)
    semana = hoje - timedelta(days=6)
    hoje_formatado = hoje.strftime('%d/%m/%Y')
    semana_formatado = semana.strftime('%d/%m/%Y')
    total_enquetes_hoje = EnqueteClientes.objects.filter(date__date=hoje).count()
    total_enquetes_semana = EnqueteClientes.objects.filter(date__range=[semana, hoje]).count()
    soma_nota_cozinha = EnqueteClientes.objects.filter(date__date=hoje).aggregate(Sum('resp1'))['resp1__sum']
    soma_nota_atendimento = EnqueteClientes.objects.filter(date__date=hoje).aggregate(Sum('resp2'))['resp2__sum']
    soma_recomendaria = EnqueteClientes.objects.filter(date__date=hoje).aggregate(Sum('resp3'))['resp3__sum']
    soma_nota_cozinha_semana = EnqueteClientes.objects.filter(date__range=[semana, hoje]).aggregate(Sum('resp1'))['resp1__sum']
    soma_nota_atendimento_semana = EnqueteClientes.objects.filter(date__range=[semana, hoje]).aggregate(Sum('resp2'))['resp2__sum']
    soma_recomendaria_semana = EnqueteClientes.objects.filter(date__range=[semana, hoje]).aggregate(Sum('resp3'))['resp3__sum']
    '''
     Validação para evitar erros no relatório quando não há respostas
    '''
    if total_enquetes_hoje is None or soma_nota_cozinha is None:
        media_cozinha = 0
    else:
        media_cozinha = round(soma_nota_cozinha / total_enquetes_hoje, 2)
    if total_enquetes_hoje is None or soma_nota_atendimento is None:
        media_atendimento = 0
    else:
        media_atendimento = round(soma_nota_atendimento / total_enquetes_hoje, 2)
    if total_enquetes_hoje is None or soma_recomendaria is None:
        perc_recomenda = 0
        soma_recomendaria = 0
    else:
        perc_recomenda = round(soma_recomendaria * 100 / total_enquetes_hoje, 2)

    media_cozinha_semana = round(soma_nota_cozinha_semana / total_enquetes_semana, 2)
    media_atendimento_semana = round(soma_nota_atendimento_semana / total_enquetes_semana, 2)
    perc_recomenda_semana = round(soma_recomendaria_semana * 100 / total_enquetes_semana, 2)

    contexto = {
        'titulo_pagina': 'Resultado de enquetes dos clientes',
        'semana_formatado': semana_formatado,
        'hoje_formatado': hoje_formatado,
        'media_cozinha': media_cozinha,
        'media_atendimento': media_atendimento,
        'total_enquetes': total_enquetes_hoje,
        'soma_recomendaria': soma_recomendaria,
        'perc_recomenda': perc_recomenda,
        'media_cozinha_semana': media_cozinha_semana,
        'media_atendimento_semana': media_atendimento_semana,
        'total_enquetes_semana': total_enquetes_semana,
        'soma_recomendaria_semana': soma_recomendaria_semana,
        'perc_recomenda_semana': perc_recomenda_semana,
    }
    return render(request, 'gerencia/resultado_clientes.html', contexto)

@login_required(login_url='/logar/')
def resultado_enquete_funcionarios(request):
    contexto = {
        'titulo_pagina': 'Resultados de enquetes dos funcionários',
    }
    return render(request, 'gerencia/resultado_funcionarios.html', contexto)

gerencia/templates/gerencia/atualiza_item.html
{% extends 'gerencia/base_dashboard.html' %}
{% load bootstrap4 %}
{% block conteudo%}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="container-fluid">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h3 class="h3">{{ titulo }}</h3>
        </div>
        <div>
            <form action="{% url 'gerencia:atualizar_item' id_item %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form form%}
                <button type="submit" class="btn bnt-sm btn-success">Salvar</button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

gerencia/templates/gerencia/base_dashboard.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Sistema de Pedido - Restaurante Típico General Küster">
    <meta name="author" content="gkuster - gutokuster@gmail.com">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <title>{{ titulo_pagina }}</title>
  </head>

  <body>
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'gerencia:dashboard' %}">Bem Vindo, {{ usuario }}</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'gerencia:sair' %}">Sair</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'gerencia:dashboard' %}">
                  <span data-feather="home"></span>
                  Dashboard
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gerencia:listar_itens' %}">
                  <span data-feather="file"></span>
                  Itens
                </a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gerencia:configuracoes' %}">
                  <span data-feather="file"></span>
                  Configuracoes
                </a>
              </li>
            </ul>

            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Relatórios</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
              </li>
            </ul>
            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
              <span>Enquetes</span>
              <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
            </h6>
            <ul class="nav flex-column mb-2">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gerencia:resultado_enquete_clientes' %}">
                  <span data-feather="file-text"></span>
                  Clientes
                </a>
              </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'gerencia:resultado_enquete_funcionarios' %}">
                  <span data-feather="file-text"></span>
                  Funcionários
                </a>
              </li>
            </ul>
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">Dashboard</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <button class="btn btn-sm btn-outline-secondary">Share</button>
                <button class="btn btn-sm btn-outline-secondary">Export</button>
              </div>
              <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
                <span data-feather="calendar"></span>
                This week
              </button>
            </div>
          </div>

{% block conteudo %} {% endblock %}


        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/jquery-slim.min.js' %}"><\/script>')</script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
</html>

gerencia/templates/gerencia/cadastro_item.html
{% extends 'gerencia/base_dashboard.html' %}
{% load bootstrap4 %}
{% block conteudo%}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="container-fluid">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h3 class="h3">{{ titulo }}</h3>
        </div>
        <div>
            <form action="{% url 'gerencia:cadastrar_item' %}" method="POST">
                {% csrf_token %}
                {% bootstrap_form form%}
                <button type="submit" class="btn bnt-sm btn-success">Salvar</button>
            </form>
        </div>
    </div>
</main>
{% endblock %}

gerencia/templates/gerencia/configuracoes.html
{% extends 'gerencia/base_dashboard.html' %}
{% load bootstrap4 %}
{% block conteudo %}

          <h2>Configurações Gerais do Sistema</h2>
          <form action="{% url 'gerencia:salvar_configuracoes' %}" method="POST">
              {% csrf_token %}
                {% bootstrap_form form%}
              <button type="submit" class="btn bnt-sm btn-success">Salvar</button>
          </form>

{% endblock %}

gerencia/templates/gerencia/dashboard.html
{% extends 'gerencia/base_dashboard.html' %}
{% block conteudo %}

          <h3>Resumo de Pedidos</h3>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Pedidos</th>
                  <th>Cancelados</th>
                  <th>Atrasados</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>{{ total_pedidos }}</td>
                  <td>{{ total_pedidos_cancelados }}</td>
                  <td>{{ total_pedidos_atrasados }}</td>
                </tr>
              </tbody>
            </table>
          </div>
          <h3>Itens com Maior média de atraso</h3>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Item</th>
                  <th>Atrasos</th>
                  <th>Tempo Cadastrado</th>
                  <th>Tempo Médio</th>
                </tr>
              </thead>
              <tbody>
              {% for pedido_atrasado in pedidos_atrasados %}
                {% for pedido in pedidos %}
                  {% if pedido.id == pedido_atrasado.pedido_id %}
                    {% for item in itens %}
                      {% if item.id == pedido.item_id %}
                    <tr>
                      <td>{{ item.id }}</td>
                      <td>{{ item.nome }}</td>
                      <td>{{ pedido.item_id.nome }}</td>
                      <td>{{ total_pedidos_atrasados }}</td>
                      <td>{{ total_pedidos_atrasados }}</td>
                    </tr>

                  {% endif %}
                {% endfor %}
              {% endif %}
                {% endfor %}
              {% endfor %}
              </tbody>
            </table>
          </div>
{% endblock %}

gerencia/templates/gerencia/itens.html
{% extends 'gerencia/base_dashboard.html' %}
{% load static %}
{% block conteudo%}
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <div class="container-fluid">
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb
            <h3 class="h3">{{ titulo }}</h3>
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-2">
                <form action="{% url 'gerencia:cadastrar_item' %}" method="POST" class="form">
                {% csrf_token %}
                  <button class="btn btn-sm btn-success">Adicionar Item</button>
                </form>
              </div>
            </div>
        </div>
        <div class="table-responsive-fluid">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Cód Item</th>
                  <th>Nome</th>
                  <th>Tempo de Preparo</th>
                  <th>Destino</th>
                  <th>Cardápio Diário</th>
                  <th>Status</th>
                  <th>Ação</th>
                </tr>
              </thead>
              <tbody>
              {% for item in itens %}
                <tr>
                  <td>{{ item.id }}</td>
                  <td><a href="{% url 'gerencia:atualizar_item' item.id %}">{{ item.nome }}</a></td>
                  <td>{{ item.tempo_preparo }}</td>
                  <td>{{ item.destino }}</td>
                    {% if item.diario == True %}
                        <td><img src="{% static 'icons/icon-yes.svg' %}" alt="True"></td>
                    {% else %}
                        <td><img src="{% static 'icons/icon-no.svg' %}" alt="False"></td>
                    {% endif %}
                  {% if item.ativo == True %}
                        <td><img src="{% static 'icons/icon-yes.svg' %}" alt="True"></td>
                    {% else %}
                        <td><img src="{% static 'icons/icon-no.svg' %}" alt="False"></td>
                    {% endif %}
                    <td>
                        <form action="{% url 'gerencia:excluir_item' item.id %}" method="POST" class="form">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-danger">Excluir</button>
                        </form>
                    </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
        </div>


    </div>
</main>
{% endblock %}

gerencia/templates/gerencia/resultado_clientes.html
{% extends 'gerencia/base_dashboard.html' %}
{% block conteudo %}
<center>
  <main role="main" class="container">
    <h4 class="mt-5">Resultados das Enquetes (Clientes)</h4>
    <p>{{ hoje_formatado }}</p>
    <br>
      <div class="row">
        <div class="col-md-3">
          <div class="card mb-3 box-shadow">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal">Total de respostas</h4>
            </div>
            <div class="card-body">
              <p class="card-text">{{ total_enquetes }}</p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3 box-shadow">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal">Média Cozinha</h4>
              </div>
              <div class="card-body">
                <p class="card-text">{{ media_cozinha }}</p>
              </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3 box-shadow">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal">Média Atendimento</h4>
            </div>
            <div class="card-body">
              <p class="card-text">{{ media_atendimento }}</p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3 box-shadow">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal">Recomendações</h4>
            </div>
            <div class="card-body">
              <p class="card-text">{{ soma_recomendaria }} <small>( {{ perc_recomenda }}%)</small></p>
            </div>
          </div>
        </div>
      </div>
    <h4 class="mt-5">Últimos 7 dias</h4>
    <p>{{ semana_formatado }} - {{ hoje_formatado }}</p>
    <br>
      <div class="row">
        <div class="col-md-3">
          <div class="card mb-3 box-shadow">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal">Total de respostas</h4>
            </div>
            <div class="card-body">
              <p class="card-text">{{ total_enquetes_semana }}</p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3 box-shadow">
              <div class="card-header">
                <h4 class="my-0 font-weight-normal">Média Cozinha</h4>
              </div>
              <div class="card-body">
                <p class="card-text">{{ media_cozinha_semana }}</p>
              </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3 box-shadow">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal">Média Atendimento</h4>
            </div>
            <div class="card-body">
              <p class="card-text">{{ media_atendimento_semana }}</p>
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3 box-shadow">
            <div class="card-header">
              <h4 class="my-0 font-weight-normal">Recomendações</h4>
            </div>
            <div class="card-body">
              <p class="card-text">{{ soma_recomendaria_semana }} <small>( {{ perc_recomenda_semana }}%)</small></p>
            </div>
          </div>
        </div>
      </div>
      <a href="{% url 'core:index' %}" class="btn btn-primary my-2">Voltar ao início</a>
      <a href="{% url 'core:enquete_clientes' %}" class="btn btn-primary my-2">Voltar a enquete</a>
    <br>
  </main>
</center>



{% endblock %}

gerencia/templates/gerencia/resultado_funcionarios.html
{% extends 'core/base_enquete.html' %}
{% block conteudo %}
    <h3>Página em construção</h3>
<a href="{% url 'core:index' %}">Voltar</a>
{% endblock%}