core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('logar/', views.logar, name='logar'),

    # Buffet
    path('buffet/', views.buffet, name='buffet'),
    path('buffet/pedido/', views.criar_pedido, name='criar_pedido'),
    path('buffet/baixar_pedido/<int:pk>', views.baixar_pedido, name='baixar_pedido'),
    path('buffet/cancelar_pedido/', views.cancelar_pedido, name='cancelar_pedido'),
    # Cozinha
    path('cozinha_quente/', views.cozinha_quente, name='cozinha_quente'),
    path('cozinha_fria/', views.cozinha_fria, name='cozinha_fria'),
    path('buffet/liberar_pedido/<int:pk>', views.liberar_pedido, name='liberar_pedido'),
    # Enquetes
    path('enquete_clientes/', views.enquete_clientes, name='enquete_clientes'),
    path('enquete_clientes/salvar', views.salvar_enquete_clientes, name='salvar_enquete_clientes'),
    path('enquete_funcionarios/', views.enquete_funcionarios, name='enquete_funcionarios'),
    ]

gerencia/urls.py
from django.urls import path
from . import views

app_name = 'gerencia'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # Itens
    path('itens/', views.listar_itens, name='listar_itens'),
    path('itens/cadastro/', views.cadastrar_item, name='cadastrar_item'),
    path('itens/excluir/<int:pk>', views.excluir_item, name='excluir_item'),
    path('itens/atualizar/<int:pk>', views.atualizar_item, name='atualizar_item'),
    #Configurações
    path('configuracoes/', views.configuracoes, name='configuracoes'),
    path('configuracoes/salvar/', views.salvar_configuracoes, name='salvar_configuracoes'),
    path('sair/', views.sair, name='sair'),
    # Enquetes
    path('enquete_clientes/resultado', views.resultado_enquete_clientes, name='resultado_enquete_clientes'),
    path('enquete_funcionarios/resultado', views.resultado_enquete_funcionarios, name='resultado_enquete_funcionarios'),

]

pedidostipico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('dashboard/', include('gerencia.urls', namespace='gerencia')),
]

core/models.py
from django.db import models

class Item(models.Model):
    DESTINO_CHOICES = (
        ('Cozinha Fria', 'Cozinha Fria'),
        ('Cozinha Quente', 'Cozinha Quente'),
        ('Sobremesas', 'Sobremesas'),
    )
    nome = models.CharField('Nome', max_length=100)
    tempo_preparo = models.IntegerField('Tempo de Preparo (Min)')
    ativo = models.BooleanField('Ativo?', default=True)
    diario = models.BooleanField('Cardápio Diário', default=False,)
    destino = models.CharField('Cozinha Destino', max_length=14, choices=DESTINO_CHOICES)
    data_cadastro = models.DateTimeField('Data de Cadastro', auto_now_add=True)
    data_atualizacao = models.DateTimeField('Data de Atualização', auto_now=True)


    class Meta:
        verbose_name = 'Item'
        verbose_name_plural = 'Itens'


    def __str__(self):
        return self.nome


class Pedido(models.Model):
    SITUACAO_CHOICES = (
        ('Em Preparo', 'Em Preparo'),
        ('Entregue', 'Entregue'),
        ('Cancelado', 'Cancelado'),
        ('Baixado', 'Baixado'),
        ('Atrasado', 'Atrasado'),
    )
    item = models.ForeignKey(Item, verbose_name='Item', on_delete=models.CASCADE)
    situacao = models.CharField('Situação', max_length=10, choices=SITUACAO_CHOICES, default='Em Preparo')
    quantidade = models.IntegerField('Quantidade')
    hora_pedido = models.DateTimeField('Hora do Pedido', auto_now_add=True)
    hora_situacao = models.DateTimeField('Situação Alterada', auto_now=True)
    hora_entrega = models.DateTimeField('Hora Entrega', auto_now=True)
    limite_entrega = models.TimeField('Limite da Entrega', auto_now_add=False, blank=True, null=True)
    tempo_restante = models.TimeField('Tempo Restante', auto_now_add=False, blank=True, null=True)


    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return self.item.nome

class PedidoAtrasado(models.Model):
    pedido = models.ForeignKey(Pedido, verbose_name='Pedido', on_delete=models.CASCADE)
    tempo_atraso = models.TimeField('Tempo de Atraso', auto_now_add=False, blank=True, null=True)
    data_atraso = models.DateTimeField('Data', auto_now_add=True)

    class Meta:
        verbose_name = 'Pedido Atrasado'
        verbose_name_plural = 'Pedidos Atrasados'

    def __str__(self):
        return self.pedido.item

class EnqueteClientes(models.Model):
    date = models.DateTimeField('Data da Resposta', auto_now_add=True)
    resp1 = models.IntegerField('Nota Cozinha')
    resp2 = models.IntegerField('Nota Atendimento')
    resp3 = models.BooleanField('Recomendaria?', default=True)

    class Meta:
        verbose_name = 'Enquete Cliente'
        verbose_name_plural = 'Enquetes Clientes'

class EnqueteFuncionarios(models.Model):
    date = models.DateTimeField('Data da Resposta', auto_now_add=True)
    resp1 = models.IntegerField('Resposta 1')
    resp2 = models.IntegerField('Resposta 2')
    resp3 = models.BooleanField('Resposta 3', default=True)

    class Meta:
        verbose_name = 'Enquete Funcionários'
        verbose_name_plural = 'Enquetes Funcionários'

core/forms.py
from django import forms
from .models import Pedido, Item

class PedidoForm(forms.ModelForm):
    SITUACAO_CHOICES = (
        ('Em Preparo', 'Em Preparo'),
        ('Entregue', 'Entregue'),
        ('Cancelado', 'Cancelado'),
        ('Baixado', 'Baixado'),
        ('Atrasado', 'Atrasado'),
    )
    item = forms.IntegerField(label='Item')
    situacao = forms.ChoiceField(label='Situação', choices=SITUACAO_CHOICES)
    quantidade = forms.IntegerField(label='Quantidade')

    class Meta:
        model = Pedido
        fields = '__all__'

class ItemForm(forms.ModelForm):
    DESTINO_CHOICES = (
        ('Cozinha Fria', 'Cozinha Fria'),
        ('Cozinha Quente', 'Cozinha Quente'),
        ('Sobremesas', 'Sobremesas'),
    )
    nome = forms.CharField(label='Nome', max_length=100)
    tempo_preparo = forms.IntegerField(label='Tempo de Preparo')
    ativo = forms.BooleanField(label='Ativo?', required=False)
    diario = forms.BooleanField(label='Cardápio Diário', required=False)
    destino = forms.ChoiceField(label='Cozinha Destino', choices=DESTINO_CHOICES)

    class Meta:
        model = Item
        fields = '__all__'

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Item, PedidoAtrasado, Pedido, EnqueteClientes, EnqueteFuncionarios
from gerencia.models import Configuracoes
from django.db.models import Q
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from datetime import datetime, timedelta, time
from django.contrib import messages

def atualiza_situacao_pedido(pk, hora_atual):
    pedido = get_object_or_404(Pedido, pk=pk)
    if str(pedido.tempo_restante) == '00:00:00' and pedido.situacao == 'Em Preparo':
        pedido.situacao = 'Atrasado'
        pedido_atrasado = PedidoAtrasado()
        pedido_atrasado.pedido_id = pedido.pk
        pedido.save()
        pedido_atrasado.save()


def atualiza_tempo_restante(pk, hora_atual):
    pedido = get_object_or_404(Pedido, pk=pk)
    if datetime.now().time() > pedido.limite_entrega:
        pedido.tempo_restante = time(0, 0, 0)
        pedido.situacao = 'Atrasado'
    else:
        hora = pedido.limite_entrega.hour - hora_atual.hour
        minuto = pedido.limite_entrega.minute - hora_atual.minute
        pedido.tempo_restante = time(hora, minuto, 0)

    pedido.save()


def index(request):
    contexto = {
        'titulo_pagina': 'Sistema de Pedidos'
    }
    return render(request, 'core/index.html', contexto)


def logar(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        usuario = authenticate(request, username=username, password=password)
        if usuario is not None:
            login(request, usuario)
            return redirect('gerencia:dashboard')
        else:
            form_login = AuthenticationForm()
    else:
        form_login = AuthenticationForm()
    return render(request, 'core/login.html', {'form_login': form_login})


'''
Funções Buffet
'''
def buffet(request):
    pedidos = Pedido.objects.filter(Q(situacao='Em Preparo') | Q(situacao='Atrasado') | Q(situacao='Entregue'))
    hora_atual = datetime.now().time()
    lista_pedidos = []
    for pedido in pedidos:
        lista_pedidos.append(pedido.item_id)
    contexto = {
        'titulo_pagina': 'Pedidos Buffet',
        'itens': Item.objects.filter(ativo=True).order_by('nome'),
        'pedidos': pedidos,
        'lista_pedidos': lista_pedidos,
        'configuracao': get_object_or_404(Configuracoes, pk=1),
    }
    return render(request, 'core/buffet.html', contexto)


def criar_pedido(request):
    pk = request.GET['pk']
    quantidade = request.GET['quantidade']
    item = get_object_or_404(Item, pk=pk)
    pedido = Pedido(item=item, quantidade=quantidade)
    minutos = str(item.tempo_preparo)
    pedido.limite_entrega = datetime.now() + timedelta(minutes=int(minutos))
    pedido.hora_entrega = pedido.limite_entrega
    pedido.save()
    return redirect('core:buffet')


def baixar_pedido(request, pk):
    pedido = get_object_or_404(Pedido, pk=pk)
    if pedido.situacao == 'Entregue':
        pedido.situacao = 'Baixado'
        pedido.save()
    return redirect('core:buffet')


def cancelar_pedido(request):
    pk = request.GET['pk']
    print('cancelando', pk)
    pedido = get_object_or_404(Pedido, pk=pk)
    pedido.situacao = 'Cancelado'
    pedido.save()
    return redirect('core:buffet')


'''
Funções Cozinha
'''
def cozinha_quente(request):
    pedidos = Pedido.objects.filter(Q(situacao='Em Preparo') | Q(situacao='Atrasado'))
    hora_atual = datetime.now().time()
    itens = Item.objects.filter(destino='Cozinha Quente')
    if pedidos.count() > 0:
        for pedido in pedidos:
            atualiza_tempo_restante(pedido.id, hora_atual)
    contexto = {
        'titulo_pagina': 'Pedidos Cozinha Quente',
        'pedidos': pedidos,
        'itens': itens,
        'configuracao': get_object_or_404(Configuracoes, pk=1),
    }
    return render(request, 'core/cozinha.html', contexto)


def cozinha_fria(request):
    pedidos = Pedido.objects.filter(Q(situacao='Em Preparo') | Q(situacao='Atrasado'))
    itens = Item.objects.filter(Q(destino='Cozinha Fria') | Q(destino='Sobremesas'))
    hora_atual = datetime.now().time()
    #tempo_restante = hora_atual - pedido.limite_entrega
    if pedidos.count() > 0:
        for pedido in pedidos:
            atualiza_tempo_restante(pedido.id, hora_atual)

    contexto = {
        'titulo_pagina': 'Pedidos Cozinha Fria',
        'pedidos': pedidos,
        'itens': itens,
        'configuracao': get_object_or_404(Configuracoes, pk=1),
    }
    return render(request, 'core/cozinha.html', contexto)


def liberar_pedido(request, pk):
    pedido = get_object_or_404(Pedido, pk=pk)
    item = get_object_or_404(Item, pk=pedido.item_id)
    if pedido.situacao == 'Atrasado':
        hora = int(pedido.limite_entrega.strftime('%H:%M')[0:2])
        minuto = int(pedido.limite_entrega.strftime('%H:%M')[3:5])
        tempo_atraso = (datetime.today() - timedelta(hours=hora, minutes=minuto)).strftime('%H:%M:%S')
        pedido_atrasado = PedidoAtrasado(pedido=pedido, tempo_atraso=tempo_atraso)
        pedido_atrasado.save()
    pedido.situacao = 'Entregue'
    pedido.save()
    if item.destino == 'Cozinha Quente':
        return redirect('core:cozinha_quente')
    else:
        return redirect('core:cozinha_fria')


'''
Funções Enquete Funcionários
'''
def enquete_funcionarios(request):
    contexto = {
        'titulo_pagina': 'Enquetes Funcionários',
    }
    return render(request, 'core/enquete_funcionarios.html', contexto)

'''
Funções Enquetes Clientes
'''
def enquete_clientes(request):
    contexto = {
        'nome': 'Enquete Clientes',
    }
    return render(request, 'core/enquete_clientes.html', contexto)


def salvar_enquete_clientes(request):
    nota_cozinha = request.POST['nota_cozinha']
    nota_atendimento = request.POST['nota_atendimento']
    recomendaria = request.POST['recomendaria']
    resposta = EnqueteClientes(resp1=nota_cozinha, resp2=nota_atendimento, resp3=recomendaria )
    resposta.save()
    messages.success(request, 'Muito obrigado pela participação!')
    return redirect('core:enquete_clientes')

def resultado_enquete_clientes(request):
    hoje = datetime.now(tz=timezone.utc)
    semana = hoje - timedelta(days=6)
    hoje_formatado = hoje.strftime('%d/%m/%Y')
    semana_formatado = semana.strftime('%d/%m/%Y')
    total_enquetes_hoje = EnqueteClientes.objects.filter(date__date=hoje).count()
    total_enquetes_semana = EnqueteClientes.objects.filter(date__range=[semana, hoje]).count()
    soma_nota_cozinha = EnqueteClientes.objects.filter(date__date=hoje).aggregate(Sum('resp1'))['resp1__sum']
    soma_nota_atendimento = EnqueteClientes.objects.filter(date__date=hoje).aggregate(Sum('resp2'))['resp2__sum']
    soma_recomendaria = EnqueteClientes.objects.filter(date__date=hoje).aggregate(Sum('resp3'))['resp3__sum']
    soma_nota_cozinha_semana = EnqueteClientes.objects.filter(date__range=[semana, hoje]).aggregate(Sum('resp1'))['resp1__sum']
    soma_nota_atendimento_semana = EnqueteClientes.objects.filter(date__range=[semana, hoje]).aggregate(Sum('resp2'))['resp2__sum']
    soma_recomendaria_semana = EnqueteClientes.objects.filter(date__range=[semana, hoje]).aggregate(Sum('resp3'))['resp3__sum']
    '''
     Validação para evitar erros no relatório quando não há respostas
    '''
    if total_enquetes_hoje is None or soma_nota_cozinha is None:
        media_cozinha = 0
    else:
        media_cozinha = round(soma_nota_cozinha / total_enquetes_hoje, 2)
    if total_enquetes_hoje is None or soma_nota_atendimento is None:
        media_atendimento = 0
    else:
        media_atendimento = round(soma_nota_atendimento / total_enquetes_hoje, 2)
    if total_enquetes_hoje is None or soma_recomendaria is None:
        perc_recomenda = 0
        soma_recomendaria = 0
    else:
        perc_recomenda = round(soma_recomendaria * 100 / total_enquetes_hoje, 2)

    media_cozinha_semana = round(soma_nota_cozinha_semana / total_enquetes_semana, 2)
    media_atendimento_semana = round(soma_nota_atendimento_semana / total_enquetes_semana, 2)
    perc_recomenda_semana = round(soma_recomendaria_semana * 100 / total_enquetes_semana, 2)

    contexto = {
        'titulo_pagina': 'Resultado de enquetes dos clientes',
        'semana_formatado': semana_formatado,
        'hoje_formatado': hoje_formatado,
        'media_cozinha': media_cozinha,
        'media_atendimento': media_atendimento,
        'total_enquetes': total_enquetes_hoje,
        'soma_recomendaria': soma_recomendaria,
        'perc_recomenda': perc_recomenda,
        'media_cozinha_semana': media_cozinha_semana,
        'media_atendimento_semana': media_atendimento_semana,
        'total_enquetes_semana': total_enquetes_semana,
        'soma_recomendaria_semana': soma_recomendaria_semana,
        'perc_recomenda_semana': perc_recomenda_semana,
    }
    return render(request, 'gerencia:resultado_clientes.html', contexto)
'''
    total_enquetes = EnqueteClientes.objects.all().count()

'''

'''
TODO: Verificar situações sem resposta
'''

core/templates/core/buffet.html
{% extends 'core/base.html' %}
{% block conteudo %}
<header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:buffet' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Cardápio</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <!-- Begin page content -->

<br>

    <main role="main" class="container-fluid">
        <br>
      <h1 class="mt-5">Típico General Küster</h1>
      <p class="lead">Itens Disponíveis</p>
      <div class="row">
            {% for item in itens %}
        <div class="col-md-2">
          <div class="card mb-4 box-shadow">
            {% if item.id in lista_pedidos%}
                {% for pedido in pedidos %}
                    {% if pedido.item_id == item.id %}
                        <div class="card-body">
                            <center>
                                <form action="{% url 'core:baixar_pedido' pedido.id %}" method="POST">
                                    {% csrf_token %}
                                    {% if pedido.situacao == 'Atrasado' %}
                                        <button type="submit" class="btn btn-block btn-danger">
                                        {% if item.nome|length > 5 %}
                                            <font style="font-size:12px">{{ pedido.quantidade }}x {{ item.nome }}</font>
                                        {% else %}
                                            {{ pedido.quantidade }}x {{ item.nome }}
                                        </button>
                                        {% endif %}
                                    {% elif pedido.situacao == 'Em Preparo' %}
                                        <button type="submit" class="btn btn-block btn-info">
                                            {% if item.nome|length > 5 %}
                                            <font style="font-size:12px">{{ pedido.quantidade }}x {{ item.nome }}</font>
                                        {% else %}
                                            {{ pedido.quantidade }}x {{ item.nome }}
                                        </button>
                                        {% endif %}
                                        </button>
                                    {% elif pedido.situacao == 'Entregue' %}
                                        <button type="submit" class="btn btn-block btn-success">
                                            {% if item.nome|length > 5 %}
                                            <font style="font-size:12px">{{ pedido.quantidade }}x {{ item.nome }}</font>
                                        {% else %}
                                            {{ pedido.quantidade }}x {{ item.nome }}
                                        </button>
                                        {% endif %}
                                        </button>
                                    {% endif %}
                                </form>
                            </center>
                        </div>
                        <div class="card-footer">
                                Previsão: {{ pedido.limite_entrega }}
                            &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                                <button type="submit" class="btn btn-danger" onclick="cancelar_pedido({{ pedido.id }})">Cancelar</button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <div class="card-body">
                    <center>
                        <button type="submit" class="btn btn-block btn-secondary" onclick="quantidade_item({{ item.id }})">
                        {% if item.nome|length > 5 %}
                            <font style="font-size:12px">{{ item.nome }}</font>
                            {% else %}
                            {{ item.nome }}
                            {% endif %}
                        </button>
                    </center>
                </div>
                <div class="card-footer">
                    <center>
                       Preparo: {{ item.tempo_preparo }} Min
                    </center>
                </div>
           {% endif %}
          </div>
        </div>
            {% endfor %}
      </div>

    </main>
    <script>
        function quantidade_item(pk_item) {
            var quantidade=prompt("Quantidade:", 1);
            if (quantidade!=null) {
                url = "{% url 'core:criar_pedido' %}";
                window.location = url + "?pk=" + pk_item + "&quantidade=" + quantidade;
            }
        }
        </script>
    <script>
        function cancelar_pedido(pk_pedido) {
            var resp=confirm("O pedido será cancelado!\n Deseja continuar?");
            if (resp == true) {
               var url = "{% url 'core:cancelar_pedido' %}";
               window.location = url + "?pk=" + pk_pedido;
            }
        }
    </script>

{% endblock %}

core/templates/core/buffet150821.html
{% extends 'core/base.html' %}
{% block conteudo %}
<header>
      <!-- Fixed navbar -->
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:buffet' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Cardápio</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <!-- Begin page content -->

<br>

    <main role="main" class="container-fluid">
        <br>
      <h1 class="mt-5">Típico General Küster</h1>
      <p class="lead">Pedidos em Aberto</p>
      <div class="row">
            {% for pedido in pedidos %}
        <div class="col-md-2">
          <div class="card mb-4 box-shadow">
              <div class="card-body">
                  {% for item in itens %}
                    {% if item.id == pedido.item_id %}
                        <form action="{% url 'core:baixar_pedido' pedido.id %}" method="POST">
                            {% csrf_token %}
                            {% if pedido.situacao == 'Atrasado' %}
                                <button type="submit" class="btn btn-block btn-danger">{{ pedido.quantidade }}x {{ item.nome }}</input>
                            {% elif pedido.situacao == 'Em Preparo' %}
                                <button type="submit" class="btn btn-block btn-info">{{ pedido.quantidade }}x {{ item.nome }}</button>
                            {% elif pedido.situacao == 'Entregue' %}
                                <button type="submit" class="btn btn-block btn-success">{{ pedido.quantidade }}x {{ item.nome }}</button>
                            {% endif %}
                        </form>
              </div>
              <div class="card-footer">
                  <center>
                      Previsão: {{ pedido.limite_entrega }} ({{ item.tempo_preparo }})
                        <button type="submit" class="btn btn-sm btn-danger" onclick="cancelar_pedido({{ pedido.id }})">Cancelar</button>
                  </center>
              </div>
                   {% endif %}
                  {% endfor %}
          </div>
        </div>
            {% endfor %}
      </div>
      <p class="lead">Itens disponíveis</p>
      <div class="row">
              {% for item in itens %}
                  {% if item.id in lista_teste %}

        <div class="col-md-2">
          <div class="card mb-4 box-shadow">
              <div class="card-body">
                  {% for item in itens %}
                    {% if item.id == pedido.item_id %}
                        <form action="{% url 'core:baixar_pedido' pedido.id %}" method="POST">
                            {% csrf_token %}
                            {% if pedido.situacao == 'Atrasado' %}
                                <button type="submit" class="btn btn-block btn-danger">{{ pedido.quantidade }}x {{ item.nome }}</input>
                            {% elif pedido.situacao == 'Em Preparo' %}
                                <button type="submit" class="btn btn-block btn-info">{{ pedido.quantidade }}x {{ item.nome }}</button>
                            {% elif pedido.situacao == 'Entregue' %}
                                <button type="submit" class="btn btn-block btn-success">{{ pedido.quantidade }}x {{ item.nome }}</button>
                            {% endif %}
                        </form>
              </div>
              <div class="card-footer">
                  <center>
                      Previsão: {{ pedido.limite_entrega }} ({{ item.tempo_preparo }})
                        <button type="submit" class="btn btn-sm btn-danger" onclick="cancelar_pedido({{ pedido.id }})">Cancelar</button>
                  </center>
              </div>
                   {% endif %}
                  {% endfor %}
          </div>
        </div>
        {% endif %}
              {% endfor %}

      </div>
    </main>
    <script>
        function quantidade_item(pk_item) {
            var quantidade=prompt("Quantidade:", 1);
            if (quantidade!=null) {
                url = "{% url 'core:criar_pedido' %}";
                window.location = url + "?pk=" + pk_item + "&quantidade=" + quantidade;
            }
        }
        </script>
    <script>
        function cancelar_pedido(pk_pedido) {
            var resp=confirm("O pedido será cancelado!\n Deseja continuar?");
            if (resp == true) {
               var url = "{% url 'core:cancelar_pedido' %}";
               window.location = url + "?pk=" + pk_pedido;
            }
        }
    </script>

{% endblock %}

core/templates/core/enquete_funcionarios.html
{% extends 'core/base_enquete.html' %}
{% block conteudo %}
    <h3>Página em construção</h3>
<a href="{% url 'core:index' %}">Voltar</a>
{% endblock%}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block conteudo %}
<main role="main" class="container">
      <h1 class="mt-5">Típico General Küster</h1>
      <p class="lead">Selecione uma opção: </p>
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <a href="{% url 'core:buffet' %}">
              <div class="card-body">
                <p class="card-text">Buffet</p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <a href="{% url 'core:cozinha_quente' %}">
              <div class="card-body">
                <p class="card-text">Cozinha Quente</p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <a href="{% url 'core:cozinha_fria' %}">
              <div class="card-body">
                <p class="card-text">Cozinha Fria</p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <a href="{% url 'core:logar' %}">
              <div class="card-body">
                <p class="card-text">Login</p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <a href="{% url 'core:enquete_clientes' %}">
              <div class="card-body">
                <p class="card-text">Enquete Clientes</p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <a href="{% url 'core:enquete_funcionarios' %}">
              <div class="card-body">
                <p class="card-text">Enquete Interna</p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <a href="{% url 'gerencia:resultado_enquete_clientes' %}">
              <div class="card-body">
                <p class="card-text">Resultados Enquete Clientes</p>
              </div>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <a href="{% url 'gerencia:resultado_enquete_funcionarios' %}">
              <div class="card-body">
                <p class="card-text">Resultados Enquete Interna</p>
              </div>
            </a>
          </div>
        </div>
      </div>
    </main>

{% endblock %}